# Generated by Django 3.2 on 2024-08-17 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeye_print_log_models',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
