# Generated by Django 3.2 on 2024-08-17 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mw', '0004_aeye_ptm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeye_ptm_models',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aeye_ptm_models',
            name='message',
            field=models.CharField(max_length=10000),
        ),
    ]
